version: 2
registries:
  npm-registry-npm-pkg-github-com-short-io:
    type: npm-registry
    url: https://npm.pkg.github.com/short-io
    token: "${{secrets.NPM_REGISTRY_NPM_PKG_GITHUB_COM_SHORT_IO_TOKEN}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  registries:
  - npm-registry-npm-pkg-github-com-short-io
